version: '3'

services:
  frontend:
    build: 
      context: ./froentend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./sqlite:/app/sqlite  

  