# Use the official Python image as base
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file and install the required Python packages
COPY requirements.txt .
RUN pip install -r requirements.txt


# Copy all app files to the working directory in the container
COPY . .

# Run the FastAPI app when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]